---

- hosts: hadoopCluster
  connection: ssh
  become: true
   
  vars:
    user: training
    node0: elephant
    node1: horse
    node2: monkey
    node3: tiger
    node4: lion
    epel_repo: http://dl.fedoraproject.org/pub/archive/epel/5/i386//epel-release-5-4.noarch.rpm
    
  tasks:
    - name: Clean up cache
      shell: yum clean all
      
    - name: Install necessary packages
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
        - nano
        - wget
        - perl
        - java-1.7.0-openjdk
        - ntp
        - libselinux-python
        - nscd
        - ansible
        - git

    - name: Config SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin yes' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication yes' } 
        - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes' }
        - { regexp: '^#RSAAuthentication', line: 'RSAAuthentication yes' }
        - { regexp: '^#PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }  

    - name: Remove persistent net rules
      file:
        path: '/etc/udev/rules.d/70-persistent-net.rules'
        state: absent                  
        
    - name: Config umask
      lineinfile:
        path: /root/.bashrc
        regexp: '^umask '
        line: 'umask 022'
        state: present
        
    - name: Source bashrc
      shell: source /root/.bashrc
              
    - name: Start NTP service
      service: name=ntpd enabled=yes state=started

    - name: Disable SELinux      
      selinux: state=disabled

    - name: Disable Iptables
      service: name=iptables enabled=no state=stopped
      
    - name: Set Swapiness to 1
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
        
    - name: Start NSCD service
      service: name=nscd enabled=yes state=started
        
    - name: Config NSCD service
      command: chkconfig --level 345 nscd on
    
    - name: Set File Handle Limits
      pam_limits:
        domain: '{{ item.domain }}'
        limit_type: hard
        limit_item: '{{ item.item }}'
        value: 32768
      with_items:
        - { domain: '^hdfs', item: 'nofile' }
        - { domain: '^hdfs', item: 'nproc' }
        - { domain: '^mapred', item: 'nofile' }
        - { domain: '^mapred', item: 'nproc' }
        - { domain: '^hbase', item: 'nofile' }
        - { domain: '^hbase', item: 'nproc' }

    - name: Config 'hdfs' user
      lineinfile:
        path: /etc/profile
        regexp: '^export HADOOP_USER_NAME'
        line: 'export HADOOP_USER_NAME=hdfs'
        state: present
              
    - name: Source /etc/profile
      shell: source /etc/profile

    - name: Edit Ansible hosts file
      blockinfile:
        path: /etc/ansible/hosts
        regexp: '^\[hadoopCluster\]'
        state: present
        block: |
          [hadoopCluster]
          {{ node0 }} hostname={{ node0 }} user={{ user }}
          {{ node1 }} hostname={{ node1 }} user={{ user }}
          {{ node2 }} hostname={{ node2 }} user={{ user }}
          {{ node3 }} hostname={{ node3 }} user={{ user }}
          {{ node4 }} hostname={{ node4 }} user={{ user }}

    - name: Restart SSHD service
      service: name=sshd enabled=yes state=restarted

