---

- hosts: hadoopCluster
  connection: ssh
  become: true

  tasks:
    - name: Update yum packages in all nodes
      yum:
        name: '*'
        state: latest
        update_cache: yes
        
