---

- hosts: localhost
  connection: local
  become: true

  vars:
    hostname: centos_template
    gateway_address: 192.168.228.2
    ip_address: 192.168.228.99

  tasks:
    - name: Install necessary packages
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
        - nano
        - wget
        - perl
        - java-1.7.0-openjdk

    - name: Config Eth0 Network Adapdter
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^BOOTPROTO', line: 'BOOTPROTO=static' }
        - { regexp: '^IPADDR', line: 'IPADDR={{ ip_address }}' }       
        - { regexp: '^ONBOOT', line: 'ONBOOT=yes' }
        - { regexp: '^NETMASK', line: 'NETMASK=255.255.255.0' }
 
    - name: Stop Eth1 Network Adapter
      command: ifconfig eth1 down
      register: command_result
      ignore_errors: True

    - name: Remove persistent net rules
      file:
        path: '/etc/udev/rules.d/70-persistent-net.rules'
        state: absent

    - name: Add nameserver to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver	{{ gateway_address }}'

    - name: Config HOSTNAME & GATEWAY
      lineinfile: 
        path: /etc/sysconfig/network
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        state: present
      with_items:
        - { regexp: '^NETWORKING', line: 'NETWORKING=yes' }
        - { regexp: '^GATEWAY', line: 'GATEWAY={{ gateway_address }}' }
        - { regexp: '^HOSTNAME', line: 'HOSTNAME={{ hostname }}' }

    - name: Add HOSTNAME to /etc/host
      lineinfile:
        path: /etc/hosts
        regexp: '^{{ ip_address }}'
        line: '{{ ip_address }}	{{ hostname }}'
        state: present
